import { ProductProvider } from "@/context/ProductContext";
import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='flex min-h-screen bg-gray-100 '
        >
        <ProductProvider>

        <Sidebar/>
          
        <div className="flex flex-col flex-1">
          <Navbar/>
          <main className="p-6">
            {children}

          </main>
        </div>
       
        </ProductProvider>
      </body>
    </html>
  );
}
